### ISSUE TITLE
ImportError: cannot import name 'Merge'

### ISSUE THREAD

**Issue by ahmadmubashir** [akshay107/CNN-QA#1]
I am facing this problem using your code. How we can fix it? The package couldn't imported. Please help.

Thanks
Best Regards

**Comment by akshay107** [comment]
The code was written on an earlier version of Keras. The current version doesn't have a separate Merge Layer (https://stackoverflow.com/questions/51031519/cant-import-keras-layers-merge). Anyways, since the Merge layer is not being used in model.py so you can remove that particular import.
